/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    DSideBar: typeof import('./src/components/Navigation/DSideBar.vue')['default']
    GroupTreeItem: typeof import('./src/components/Trees/groupTreeItem.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TestUI: typeof import('./src/components/TestUI/index.vue')['default']
    TodoDetail: typeof import('./src/components/Table/TodoDetail.vue')['default']
    TodoList: typeof import('./src/components/Table/TodoList.vue')['default']
    TreeItem: typeof import('./src/components/Trees/treeItem.vue')['default']
    Trees: typeof import('./src/components/Trees/index.vue')['default']
    TSideBar: typeof import('./src/components/Navigation/TSideBar.vue')['default']
  }
}
