export enum ModalEventNameEnum {
  CLOSED ='CLOSED',
  UNCLOSED ='UNCLOSED',
  OPEN = 'OPEN',
  START = 'START',
  CREATE = 'CREATE',
  CREATECHILD = 'CREATECHILD',
  SHARE = 'SHARE',
  RECORD = 'RECORD',
  DELETE = 'DELETE',
  DELETEChILD = 'DELETEChILD'
  // DETAIL = 'DETAIL',
  // UP = 'UP',
  // DOWN = 'DOWN',
  // TOP = 'TOP',
  // BOTTOM = 'BOTTOM'
}
